spring:
  cloud:
    gateway:
      discovery:
          locator:
            enabled: true
            lower-case-service-id: true
      routes:
        - id: service3
          uri: lb://SERVICE3
          predicates:
            - Path=/service3/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/