logging:
  level:
    root: INFO
    org.springframework: WARN
    com.robolverap: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics #Expone los endpoints de Actuator para health, info y metrics.
  endpoint:
    health:
      show-details: always #Configura el endpoint de health para mostrar siempre detalles completos.

eureka:
  client:
    registerWithEureka: true #para que el cliente se registre con el servidor Eureka.
    fetchRegistry: true #para que el cliente obtenga el registro de Eureka.
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #si esta en tre Usa la dirección IP en lugar del hostname al registrarse con Eureka.
    instance-id: ${spring.application.name}:${random.uuid} #Genera un ID único para cada instancia del servicio.
    leaseRenewalIntervalInSeconds: 30 #Intervalo en segundos en el que el cliente debe enviar renovaciones al servidor Eureka.
    leaseExpirationDurationInSeconds: 90 #Tiempo en segundos tras el cual el servidor Eureka caducará la instancia si no recibe renovaciones.

# spring:
#   security:
#     user:
#       name: ${SECURITY_USER:user}
#       password: ${SECURITY_PASSWORD:password}

server:
  port: 0  # Asigna un puerto aleatorio al iniciar la aplicación.
  servlet:
    context-path: /api #Establece un prefijo "/api" para todas las rutas del servicio.


spring:
  jackson:
    time-zone: America/Mexico_City #Configura la zona horaria para la serialización/deserialización JSON a la de la Ciudad de México.